name: Linterns

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: lint-flake8
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: LintWithFlake8
        uses: py-actions/flake8@v2
        with:
          ignore: "F401"
          exclude: "**/migrations/**"
          max-line-length: "120"
