name: Pytest

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: PyTests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: Install and upgrade packaging tools
        run: python -m pip install -r requirements.txt
      - name: Run tests
        run: pytest
